"""
Variable definitions for 100 socioeconomic archetype dimensions.
Used to generate unique archetype profiles.
"""

ARCHETYPE_VARIABLES = {
    1: {"name": "Income level", "values": ["very low", "low", "middle", "high", "very high"]},
    2: {"name": "Wealth level", "values": ["none", "limited", "moderate", "high"]},
    3: {"name": "Education level", "values": ["none", "high school", "college", "graduate"]},
    4: {"name": "Occupation sector", "values": ["service", "manual", "professional", "management"]},
    5: {"name": "Employment stability", "values": ["unstable", "contract", "stable"]},
    6: {"name": "Employment type", "values": ["full-time", "part-time", "gig", "unemployed"]},
    7: {"name": "Industry", "values": ["agriculture", "manufacturing", "retail", "tech"]},
    8: {"name": "Job seniority", "values": ["entry-level", "mid-career", "senior"]},
    9: {"name": "Union membership", "values": ["none", "member", "leadership"]},
    10: {"name": "Career mobility", "values": ["low", "medium", "high"]},
    11: {"name": "Age group", "values": ["child", "youth", "young adult", "mid-career", "senior"]},
    12: {"name": "Gender identity", "values": ["male", "female", "nonbinary"]},
    13: {"name": "Sexual orientation", "values": ["heterosexual", "LGBTQ"]},
    14: {"name": "Race/ethnicity", "values": ["majority", "minority"]},
    15: {"name": "Immigration status", "values": ["citizen", "permanent resident", "visa", "undocumented"]},
    16: {"name": "Country of birth", "values": ["domestic", "foreign-born"]},
    17: {"name": "Years since immigration", "values": ["<5", "5–15", "15+"]},
    18: {"name": "Language proficiency", "values": ["fluent", "intermediate", "limited"]},
    19: {"name": "Primary language", "values": ["English", "Spanish", "Mandarin", "other"]},
    20: {"name": "Cultural integration", "values": ["low", "medium", "high"]},
    21: {"name": "Marital status", "values": ["single", "married", "divorced", "widowed"]},
    22: {"name": "Household size", "values": ["1", "2–3", "4–5", "6+"]},
    23: {"name": "Number of children", "values": ["none", "1–2", "3+"]},
    24: {"name": "Single parent status", "values": ["yes", "no"]},
    25: {"name": "Elder dependents", "values": ["none", "one", "multiple"]},
    26: {"name": "Household income diversity", "values": ["single earner", "dual earner"]},
    27: {"name": "Household stability", "values": ["stable", "unstable"]},
    28: {"name": "Childcare access", "values": ["none", "limited", "reliable"]},
    29: {"name": "Family wealth support", "values": ["none", "moderate", "strong"]},
    30: {"name": "Intergenerational mobility", "values": ["downward", "stable", "upward"]},
    31: {"name": "Physical health", "values": ["poor", "moderate", "good"]},
    32: {"name": "Mental health", "values": ["poor", "moderate", "good"]},
    33: {"name": "Chronic illness", "values": ["none", "mild", "severe"]},
    34: {"name": "Disability status", "values": ["none", "physical", "cognitive"]},
    35: {"name": "Health insurance", "values": ["none", "public", "private"]},
    36: {"name": "Healthcare access", "values": ["limited", "moderate", "strong"]},
    37: {"name": "Healthcare affordability", "values": ["unaffordable", "manageable"]},
    38: {"name": "Substance abuse risk", "values": ["low", "moderate", "high"]},
    39: {"name": "Life expectancy risk", "values": ["low", "medium", "high"]},
    40: {"name": "Preventive care usage", "values": ["rare", "occasional", "regular"]},
    41: {"name": "Housing status", "values": ["owner", "renter", "homeless"]},
    42: {"name": "Housing stability", "values": ["stable", "unstable"]},
    43: {"name": "Housing affordability", "values": ["affordable", "burdened"]},
    44: {"name": "Neighborhood income level", "values": ["low", "mixed", "high"]},
    45: {"name": "Neighborhood safety", "values": ["unsafe", "moderate", "safe"]},
    46: {"name": "Housing quality", "values": ["poor", "adequate", "high"]},
    47: {"name": "Exposure to pollution", "values": ["low", "medium", "high"]},
    48: {"name": "Access to green space", "values": ["low", "medium", "high"]},
    49: {"name": "Disaster risk exposure", "values": ["low", "moderate", "high"]},
    50: {"name": "Infrastructure quality", "values": ["poor", "moderate", "strong"]},
    51: {"name": "Geography type", "values": ["rural", "suburban", "urban"]},
    52: {"name": "Population density", "values": ["low", "medium", "high"]},
    53: {"name": "Region economic growth", "values": ["declining", "stable", "growing"]},
    54: {"name": "Transportation access", "values": ["limited", "moderate", "strong"]},
    55: {"name": "Commute time", "values": ["short", "medium", "long"]},
    56: {"name": "Access to public transit", "values": ["none", "limited", "extensive"]},
    57: {"name": "Distance to employment centers", "values": ["near", "moderate", "far"]},
    58: {"name": "Internet access", "values": ["none", "slow", "high-speed"]},
    59: {"name": "Local job availability", "values": ["low", "medium", "high"]},
    60: {"name": "Local cost of living", "values": ["low", "moderate", "high"]},
    61: {"name": "Access to quality schools", "values": ["low", "medium", "high"]},
    62: {"name": "Access to higher education", "values": ["low", "medium", "high"]},
    63: {"name": "Access to job training", "values": ["none", "limited", "strong"]},
    64: {"name": "Legal representation access", "values": ["none", "limited", "reliable"]},
    65: {"name": "Access to social services", "values": ["limited", "moderate", "strong"]},
    66: {"name": "Banking access", "values": ["unbanked", "basic", "full"]},
    67: {"name": "Credit access", "values": ["poor", "moderate", "strong"]},
    68: {"name": "Political representation", "values": ["low", "moderate", "high"]},
    69: {"name": "Voting access", "values": ["limited", "moderate", "easy"]},
    70: {"name": "Government trust", "values": ["low", "medium", "high"]},
    71: {"name": "Social network size", "values": ["small", "medium", "large"]},
    72: {"name": "Community support", "values": ["weak", "moderate", "strong"]},
    73: {"name": "Religious community participation", "values": ["none", "occasional", "active"]},
    74: {"name": "Civic participation", "values": ["none", "occasional", "frequent"]},
    75: {"name": "Volunteer engagement", "values": ["none", "occasional", "frequent"]},
    76: {"name": "Social isolation", "values": ["low", "moderate", "high"]},
    77: {"name": "Informal economic support", "values": ["none", "moderate", "strong"]},
    78: {"name": "Mentorship access", "values": ["none", "limited", "strong"]},
    79: {"name": "Professional network", "values": ["weak", "moderate", "strong"]},
    80: {"name": "Community leadership role", "values": ["none", "informal", "formal"]},
    81: {"name": "Job security", "values": ["low", "moderate", "high"]},
    82: {"name": "Income volatility", "values": ["high", "moderate", "low"]},
    83: {"name": "Legal vulnerability", "values": ["low", "moderate", "high"]},
    84: {"name": "Exposure to discrimination", "values": ["low", "medium", "high"]},
    85: {"name": "Exposure to policing", "values": ["low", "medium", "high"]},
    86: {"name": "Workplace power", "values": ["low", "moderate", "high"]},
    87: {"name": "Workplace safety", "values": ["unsafe", "moderate", "safe"]},
    88: {"name": "Automation risk", "values": ["low", "medium", "high"]},
    89: {"name": "Financial literacy", "values": ["low", "moderate", "high"]},
    90: {"name": "Financial resilience", "values": ["low", "medium", "high"]},
    91: {"name": "Digital literacy", "values": ["low", "moderate", "high"]},
    92: {"name": "Access to computers", "values": ["none", "shared", "personal"]},
    93: {"name": "Smartphone access", "values": ["none", "basic", "advanced"]},
    94: {"name": "Online information exposure", "values": ["limited", "moderate", "high"]},
    95: {"name": "Media consumption diversity", "values": ["low", "moderate", "high"]},
    96: {"name": "Misinformation exposure", "values": ["low", "medium", "high"]},
    97: {"name": "Remote work capability", "values": ["none", "partial", "full"]},
    98: {"name": "Online professional presence", "values": ["none", "basic", "strong"]},
    99: {"name": "Participation in digital economy", "values": ["none", "occasional", "frequent"]},
    100: {"name": "AI/automation skill exposure", "values": ["none", "basic", "advanced"]},
}
